"""Build the profile: every page from live GitHub data, and the README.

    python scripts/build.py            # from the repo root

Run daily by .github/workflows/refresh.yml with GITHUB_TOKEN, so the numbers stay real.
The banner (banner.py) is rebuilt with everything else.
"""

import urllib.request
from pathlib import Path

import banner
import data
import pages
from fontpaths import FontRef

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
FONT_DIR = Path(__file__).resolve().parent / "fonts"

FONT_FILES = {
    "Inter[opsz,wght].ttf": "ofl/inter/Inter%5Bopsz,wght%5D.ttf",
    "JetBrainsMono[wght].ttf": "ofl/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf",
}
PORTFOLIO = "https://portfolio-zeta-navy-fylz2ik8js.vercel.app/"
LINKS = (
    ("Portfolio", PORTFOLIO),
    ("LinkedIn", "https://www.linkedin.com/in/likith-lochan-2ab93b290"),
    ("Email", "mailto:likithlu3@gmail.com"),
    ("GitHub", f"https://github.com/{data.USER}?tab=repositories"),
)


def load_fonts() -> pages.Fonts:
    FONT_DIR.mkdir(exist_ok=True)
    for name, remote in FONT_FILES.items():
        if not (FONT_DIR / name).exists():
            print(f"fetching {name}")
            urllib.request.urlretrieve(f"https://raw.githubusercontent.com/google/fonts/main/{remote}", FONT_DIR / name)

    def ref(name: str, *axes: tuple[str, float]) -> FontRef:
        return FontRef(str(FONT_DIR / name), tuple(axes))

    return pages.Fonts(
        display=ref("Inter[opsz,wght].ttf", ("opsz", 32), ("wght", 800)),
        bold=ref("Inter[opsz,wght].ttf", ("opsz", 28), ("wght", 650)),
        sans=ref("Inter[opsz,wght].ttf", ("opsz", 18), ("wght", 420)),
        mono=ref("JetBrainsMono[wght].ttf", ("wght", 500)),
    )


def img(name: str, alt: str, width: str = "100%") -> str:
    """The light page, swapped for its dark twin when GitHub is in dark mode."""
    return (
        f'<picture><source media="(prefers-color-scheme: dark)" srcset="./assets/dark/{name}.svg">'
        f'<img src="./assets/{name}.svg" width="{width}" alt="{alt}"></picture>'
    )


def readme(p: data.Profile) -> str:
    buttons = " ".join(f'<a href="{url}">{img(f"link-{label.lower()}", label, "24%")}</a>' for label, url in LINKS)
    raw = f"https://raw.githubusercontent.com/{data.USER}/{data.USER}/output"
    tiles = [
        f'<a href="https://github.com/{data.USER}/{pr.repo}">{img(f"entry-{i}", f"{pr.name}: {pr.cause}", "49%")}</a>'
        for i, pr in enumerate(pages.PROJECTS, start=1)
    ]
    projects = "\n\n".join(" ".join(tiles[i:i + 2]) for i in range(0, len(tiles), 2))
    return f"""<!-- Generated by scripts/build.py. Edit the scripts, not this file. -->
<div align="center">

<a href="{PORTFOLIO}">{img("banner", "Likith Lochan. DevOps, Full-Stack, Applied AI. I build systems that ship, scale and fix themselves.")}</a>

{img("ep-01", "01: About")}

{img("about", "About me: I build it, ship it, and keep it running. DevOps and Cloud, Full-Stack, Applied AI.", "49%")} {img("whoami", "whoami: role, stack and what I have shipped", "49%")}

{img("ep-02", "02: Projects")}

{projects}

{img("ep-03", "03: Activity")}

<picture><source media="(prefers-color-scheme: dark)" srcset="{raw}/github-snake-dark.svg"><img alt="Contribution snake" src="{raw}/github-snake.svg" width="100%"></picture>

{img("ep-04", "04: Principles")}

{img("rules", "How I work: ship it, then armor it; automate the boring; verify before trusting")}

{img("ep-05", "05: Contact")}

{buttons}

</div>
"""


def main() -> None:
    f = load_fonts()
    p = data.load()
    for theme, folder in (("light", ASSETS), ("dark", ASSETS / "dark")):
        folder.mkdir(parents=True, exist_ok=True)
        pages.set_theme(theme)
        render(p, f, lambda name, svg: (folder / f"{name}.svg").write_text(svg, encoding="utf-8"))
    (ROOT / "README.md").write_text(readme(p), encoding="utf-8")
    print(f"built README and {len(list(ASSETS.rglob('*.svg')))} svgs from {'live' if p.live else 'preview'} data")


def render(p: data.Profile, f: pages.Fonts, write) -> None:
    sections = (
        ("About", "Who I am and what I work with."),
        ("Projects", "Problems I set out to solve."),
        ("Activity", "Every square is a day of work."),
        ("Principles", "How I build."),
        ("Contact", "Let's build something."),
    )
    for i, (title, line) in enumerate(sections, start=1):
        write(f"ep-{i:02d}", pages.title_card(i, title, line, f))
    write("whoami", pages.whoami(p, f))
    write("about", pages.about(f))
    for i, proj in enumerate(pages.PROJECTS, start=1):
        write(f"entry-{i}", pages.entry(p, i, proj, f))
    write("rules", pages.rules(p, f))
    for label, _ in LINKS:
        write(f"link-{label.lower()}", pages.button(label, f))
    write("banner", banner.render(f))


if __name__ == "__main__":
    main()
