"""Build the profile: every page from live GitHub data, and the README.

    python scripts/build.py            # from the repo root

Run daily by .github/workflows/refresh.yml with GITHUB_TOKEN, so the numbers stay real.
The banner is made separately by poster.py (it only changes when the artwork does).
"""

import urllib.request
from pathlib import Path

import data
import pages
from fontpaths import FontRef

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
FONT_DIR = Path(__file__).resolve().parent / "fonts"

FONT_FILES = {
    "Caveat[wght].ttf": "ofl/caveat/Caveat%5Bwght%5D.ttf",
    "GrenzeGotisch[wght].ttf": "ofl/grenzegotisch/GrenzeGotisch%5Bwght%5D.ttf",
    "UnifrakturMaguntia-Book.ttf": "ofl/unifrakturmaguntia/UnifrakturMaguntia-Book.ttf",
    "CormorantGaramond[wght].ttf": "ofl/cormorantgaramond/CormorantGaramond%5Bwght%5D.ttf",
    "CormorantGaramond-Italic[wght].ttf": "ofl/cormorantgaramond/CormorantGaramond-Italic%5Bwght%5D.ttf",
    "JetBrainsMono[wght].ttf": "ofl/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf",
    "YujiBoku-Regular.ttf": "ofl/yujiboku/YujiBoku-Regular.ttf",
}
LINKS = (
    ("LinkedIn", "https://www.linkedin.com/in/likith-lochan-2ab93b290"),
    ("Email", "mailto:likithlu3@gmail.com"),
    ("GitHub", f"https://github.com/{data.USER}?tab=repositories"),
)


def load_fonts() -> pages.Fonts:
    FONT_DIR.mkdir(exist_ok=True)
    for name, remote in FONT_FILES.items():
        if not (FONT_DIR / name).exists():
            print(f"fetching {name}")
            urllib.request.urlretrieve(f"https://raw.githubusercontent.com/google/fonts/main/{remote}", FONT_DIR / name)

    def ref(name: str, *axes: tuple[str, float]) -> FontRef:
        return FontRef(str(FONT_DIR / name), tuple(axes))

    return pages.Fonts(
        hand=ref("Caveat[wght].ttf", ("wght", 560)),
        gothic=ref("GrenzeGotisch[wght].ttf", ("wght", 640)),
        old_english=ref("UnifrakturMaguntia-Book.ttf"),
        serif=ref("CormorantGaramond[wght].ttf", ("wght", 500)),
        serif_bold=ref("CormorantGaramond[wght].ttf", ("wght", 700)),
        italic=ref("CormorantGaramond-Italic[wght].ttf", ("wght", 500)),
        mono=ref("JetBrainsMono[wght].ttf", ("wght", 500)),
        brush=ref("YujiBoku-Regular.ttf"),
    )


def img(name: str, alt: str, width: str = "100%") -> str:
    return f'<img src="./assets/{name}.svg" width="{width}" alt="{alt}">'


def readme(p: data.Profile) -> str:
    recent = [
        f'<a href="{r.url}">{img(f"recent-{i}", f"{r.name}: {r.description}", "49%")}</a>'
        for i, r in enumerate(p.repos[:4], start=1)
    ]
    rows = "\n\n".join(" ".join(recent[i:i + 2]) for i in range(0, len(recent), 2))
    buttons = " ".join(f'<a href="{url}">{img(f"link-{label.lower()}", label, "30%")}</a>' for label, url in LINKS)
    raw = f"https://raw.githubusercontent.com/{data.USER}/{data.USER}/output"
    return f"""<!-- Generated by scripts/build.py. Edit the scripts, not this file. -->
<div align="center">

{img("banner", "Likith Lochan. DevOps, Backend/Full-Stack, Applied AI.")}

{img("ep-01", "Episode 01: Identity")}

{img("identity", "Likith Lochan: live GitHub stats", "49%")} {img("deduction", "L's deduction: activity over the last 30 days", "49%")}

{img("ep-02", "Episode 02: Names")}

{img("names", "Top languages across public repositories")}

{img("ep-03", "Episode 03: Record")}

{rows}

<picture><source media="(prefers-color-scheme: dark)" srcset="{raw}/github-snake-dark.svg"><img alt="Contribution snake" src="{raw}/github-snake.svg" width="100%"></picture>

{img("ep-04", "Episode 04: Rules")}

{img("rules", "How to use it: ship it, then armor it; automate the boring; verify before trusting")}

{img("ep-05", "Episode 05: Contact")}

{buttons}

</div>
"""


def write(name: str, svg: str) -> None:
    (ASSETS / f"{name}.svg").write_text(svg, encoding="utf-8")


def main() -> None:
    f = load_fonts()
    p = data.load()
    ASSETS.mkdir(exist_ok=True)
    episodes = (
        ("正体", "Identity", "Every name has a file."),
        ("名前", "Names", "Languages written in the note."),
        ("記録", "Record", "Recent pages, and the trail they left."),
        ("掟", "Rules", "How to use it."),
        ("接触", "Contact", "Summon me."),
    )
    for i, (kanji, english, note) in enumerate(episodes, start=1):
        write(f"ep-{i:02d}", pages.title_card(i, kanji, english, note, f))
    write("identity", pages.identity(p, f))
    write("deduction", pages.deduction(p, f))
    write("names", pages.names(p, f))
    for old in ASSETS.glob("recent-*.svg"):
        old.unlink()
    for i, repo in enumerate(p.repos[:4], start=1):
        write(f"recent-{i}", pages.recent(p, repo, i, f))
    write("rules", pages.rules(p, f))
    for label, _ in LINKS:
        write(f"link-{label.lower()}", pages.button(label, f))
    if not (ASSETS / "banner.svg").exists():
        import poster
        (ASSETS / "banner.svg").write_text(poster.render(None), encoding="utf-8")
    (ROOT / "README.md").write_text(readme(p), encoding="utf-8")
    print(f"built README and {len(list(ASSETS.glob('*.svg')))} svgs from {'live' if p.live else 'preview'} data")


if __name__ == "__main__":
    main()
