"""Build the profile: every page from live GitHub data, and the README.

    python scripts/build.py            # from the repo root

Run daily by .github/workflows/refresh.yml with GITHUB_TOKEN, so the numbers stay real.
The banner (banner.py) is rebuilt with everything else.
"""

import urllib.request
from pathlib import Path

import ascii_card
import banner
import data
import note
import pages
from fontpaths import FontRef

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
FONT_DIR = Path(__file__).resolve().parent / "fonts"

FONT_FILES = {
    "Caveat[wght].ttf": "ofl/caveat/Caveat%5Bwght%5D.ttf",
    "GrenzeGotisch[wght].ttf": "ofl/grenzegotisch/GrenzeGotisch%5Bwght%5D.ttf",
    "UnifrakturMaguntia-Book.ttf": "ofl/unifrakturmaguntia/UnifrakturMaguntia-Book.ttf",
    "CormorantGaramond[wght].ttf": "ofl/cormorantgaramond/CormorantGaramond%5Bwght%5D.ttf",
    "CormorantGaramond-Italic[wght].ttf": "ofl/cormorantgaramond/CormorantGaramond-Italic%5Bwght%5D.ttf",
    "JetBrainsMono[wght].ttf": "ofl/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf",
    "YujiBoku-Regular.ttf": "ofl/yujiboku/YujiBoku-Regular.ttf",
}
PORTFOLIO = "https://portfolio-zeta-navy-fylz2ik8js.vercel.app/"
LINKS = (
    ("Portfolio", PORTFOLIO),
    ("LinkedIn", "https://www.linkedin.com/in/likith-lochan-2ab93b290"),
    ("Email", "mailto:likithlu3@gmail.com"),
    ("GitHub", f"https://github.com/{data.USER}?tab=repositories"),
)


def load_fonts() -> pages.Fonts:
    FONT_DIR.mkdir(exist_ok=True)
    for name, remote in FONT_FILES.items():
        if not (FONT_DIR / name).exists():
            print(f"fetching {name}")
            urllib.request.urlretrieve(f"https://raw.githubusercontent.com/google/fonts/main/{remote}", FONT_DIR / name)

    def ref(name: str, *axes: tuple[str, float]) -> FontRef:
        return FontRef(str(FONT_DIR / name), tuple(axes))

    return pages.Fonts(
        hand=ref("Caveat[wght].ttf", ("wght", 560)),
        gothic=ref("GrenzeGotisch[wght].ttf", ("wght", 640)),
        old_english=ref("UnifrakturMaguntia-Book.ttf"),
        serif=ref("CormorantGaramond[wght].ttf", ("wght", 500)),
        serif_bold=ref("CormorantGaramond[wght].ttf", ("wght", 700)),
        italic=ref("CormorantGaramond-Italic[wght].ttf", ("wght", 500)),
        mono=ref("JetBrainsMono[wght].ttf", ("wght", 500)),
        brush=ref("YujiBoku-Regular.ttf"),
    )


def img(name: str, alt: str, width: str = "100%") -> str:
    return f'<img src="./assets/{name}.svg" width="{width}" alt="{alt}">'


def readme(p: data.Profile) -> str:
    buttons = " ".join(f'<a href="{url}">{img(f"link-{label.lower()}", label, "24%")}</a>' for label, url in LINKS)
    raw = f"https://raw.githubusercontent.com/{data.USER}/{data.USER}/output"
    tiles = [
        f'<a href="https://github.com/{data.USER}/{pr.repo}">{img(f"entry-{i}", f"{pr.name}: {pr.cause}", "49%")}</a>'
        for i, pr in enumerate(pages.PROJECTS, start=1)
    ]
    projects = "\n\n".join(" ".join(tiles[i:i + 2]) for i in range(0, len(tiles), 2))
    return f"""<!-- Generated by scripts/build.py. Edit the scripts, not this file. -->
<div align="center">

<a href="{PORTFOLIO}">{img("banner", "Likith Lochan. DevOps, Full-Stack, Applied AI. Ryuk watching over Tokyo in the rain under a blood moon.")}</a>

{img("ep-01", "Episode 01: Identity")}

{img("note", "ASCII art: the Death Note, bleeding from its title, gripped by a shinigami's claw", "49%")} {img("whoami", "whoami: role, stack and what I have shipped", "49%")}

{img("ep-02", "Episode 02: Names")}

{projects}

{img("ep-03", "Episode 03: Record")}

<picture><source media="(prefers-color-scheme: dark)" srcset="{raw}/github-snake-dark.svg"><img alt="Contribution snake" src="{raw}/github-snake.svg" width="100%"></picture>

{img("ep-04", "Episode 04: Rules")}

{img("rules", "How to use it: ship it, then armor it; automate the boring; verify before trusting")}

{img("ep-05", "Episode 05: Contact")}

{buttons}

</div>
"""


def write(name: str, svg: str) -> None:
    (ASSETS / f"{name}.svg").write_text(svg, encoding="utf-8")


def main() -> None:
    f = load_fonts()
    p = data.load()
    ASSETS.mkdir(exist_ok=True)
    episodes = (
        ("正体", "Identity", "\u201cI'm also childish, and I hate to lose.\u201d  \u2014 L"),
        ("名前", "Names", "Every project here killed a problem."),
        ("記録", "Record", "\u201cHumans are so interesting.\u201d  \u2014 Ryuk"),
        ("掟", "Rules", "How to use it."),
        ("接触", "Contact", "Summon me."),
    )
    for i, (kanji, english, line) in enumerate(episodes, start=1):
        write(f"ep-{i:02d}", pages.title_card(i, kanji, english, line, f))
    write("whoami", pages.whoami(p, f))
    write("note", ascii_card.render(
        f, *note.arrays(f.serif_bold.path), "LIKITH@DEATHNOTE  ·  ~/DEATH-NOTE", "the human whose name is written in this note shall die",
        "ASCII art: the Death Note, bleeding from its title, gripped by a shinigami's claw"))
    for i, proj in enumerate(pages.PROJECTS, start=1):
        write(f"entry-{i}", pages.entry(p, i, proj, f))
    write("rules", pages.rules(p, f))
    for label, _ in LINKS:
        write(f"link-{label.lower()}", pages.button(label, f))
    write("banner", banner.render(f))
    (ROOT / "README.md").write_text(readme(p), encoding="utf-8")
    print(f"built README and {len(list(ASSETS.glob('*.svg')))} svgs from {'live' if p.live else 'preview'} data")


if __name__ == "__main__":
    main()
